name: caller
description: "A large dialer for older people"
publish_to: 'none'
version: 2.0.0+0

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  # phone_number: 2.0.1
  fast_contacts: 4.0.0
  permission_handler: 11.3.1
  direct_dialer: 2.0.1
  flutter_native_splash: 2.4.4
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_native_splash:
  color: "#02A008"
  color_dark: "#02A008"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#02A008"
    color_dark: "#02A008"
  android: true
  ios: false
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
